baseurl = "https://fashionunited.com"
languageCode = "en-us"
languageLang = "en"
title = "My new Victor-Hugo site"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
theme = "hugo-fashionunited-theme"

# Define how many posts should appear on a site
paginate = 10


contentdir = "content/fashionunited.com/pages"
publishdir = "dist"


[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	locale = "en-US"
	joomlaNavBar = true
	showAdsTop = true
	showAdsSide = true
	showWFB = true
	wfbCode = "COM"
	adUnitLeft = "com/jobsLandingPage_left"
	adUnitRight = "com/jobsLandingPage_right"
	adUnitTop = "com/jobsLandingPage_top"
	adUnitTopMobile = "com/jobsLandingPage_top_mobile"

[permalinks]
  page = "/:slug/"

[params.visualLanding]
  headerTitle = "Find your fashion job"
  searchForJobs = "Search for Jobs"
  AllCategories = "All categories"
  labelCategories = "Job categories"
  labelCategorie1 = "Retail Management & Instore"
  labelCategorie2 = "Sales & Marketing"
  labelCategorie3 = "Design & Creative"
  labelCategorie4 = "Product & Supply Chain"
  labelCategorie5 = "Other Jobs"
  labelCategorie6 = "Internships & Traineeships"
  labelLatestJobs = "Latest jobs"
  buttonPostJob = "Post a job"
  buttonFashionCareers = "Fashion careers"
  buttonMoreJobs = "More jobs"
  linkToJobboard = "/fashion-jobs"
  linkToCategorieAll = "/fashion-jobs"
  linkToCategorieRetail = "/fashion-jobs/retail-management-and-in-store"
  linkToCategorieSales = "/fashion-jobs/sales-and-marketing"
  linkToCategorieDesign = "/fashion-jobs/design-and-creative"
  linkToCategorieProduct = "/fashion-jobs/product-and-supply-chain"
  linkToCategorieOther = "/fashion-jobs/other"
  linkToCategorieInternships = "/fashion-jobs/internships"
  linkToPostJob = "/submit-your-job-postings"
  linkToFashionCareers = "/fashion-jobs"

 [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

 [[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10
